name: Install, Build, Deploy

on: [push, pull_request]
jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - id: yarn-cache
        name: Get Yarn cache path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Use Node.js 12.x
        uses: actions/setup-node@master
        with:
          node-version: 12.x

      - name: Load cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Linting
        run: yarn run eslint-check

      - name: Build App
        if: ${{github.repository_owner == 'CougarCS' && (github.ref == 'refs/heads/prod' || github.ref == 'refs/heads/master')}}
        run: CI=false && yarn build
        env:
          REACT_APP_STRIPE_KEY: ${{secrets.REACT_APP_STRIPE_KEY}}
          REACT_APP_RECAPTCHA_SITE_KEY: ${{secrets.REACT_APP_RECAPTCHA_SITE_KEY}}
          REACT_APP-SENTRY_PUBLIC_URL: ${{secrets.REACT_APP_SENTRY_PUBLIC_URL}}

      - name: Deploy
        if: ${{github.repository_owner == 'CougarCS' && github.ref == 'refs/heads/prod'}}
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{secrets.FTP_URL}}
          username: ${{secrets.FTP_USERNAME}}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: build
